export const STARTER_QUESTIONS = [
  'What did Martin Luther say about free will?',
  'What is the meaning of life?',
  'How do I deal with anxiety about things I cannot control?',
  'Is it ever okay to lie to protect someone?',
  'What did the Stoics teach about facing death?',
  'How do I become a better person?',
  'What is true love according to the philosophers?',
  'Why do bad things happen to good people?',
  'How do I find meaning after losing my faith?',
  'What makes an action morally right or wrong?',
  'How should I treat others according to Confucius?',
  'What did Buddha teach about suffering?',
  'Does God exist? What are the arguments?',
  'What did John Calvin teach about predestination?',
  'How can I know if I am truly saved according to the Puritans?',
  'What did John Wesley mean by a heart "strangely warmed"?',
  "What is the Christian life like according to Bunyan's Pilgrim's Progress?",
  'What did Jonathan Edwards say about religious affections?',
  'How did Spurgeon balance God\'s sovereignty with evangelism?',
  'What did the Reformers teach about grace and works?',
  'How should Christians respond to unjust rulers according to Knox?',
];
