// General questions that apply to all traditions
export const GENERAL_QUESTIONS = [
  'What is the meaning of life?',
  'How can I find true happiness?',
  'How should I live my life?',
  'What is the nature of reality?',
  'How do I know what is right and wrong?',
  'What is love?',
  'How can I deal with suffering?',
  'What is the purpose of existence?',
  'How can I become a better person?',
  'What is truth?',
  'What is justice?',
  'What is wisdom?',
  'How do I find inner peace?',
  'What is the good life?',
  'What is freedom?',
  'How should I face death?',
];

// Questions by philosophical tradition
export const QUESTIONS_BY_TRADITION: Record<string, string[]> = {
  'Ancient Greek Philosophy': [
    'What is the nature of the soul?',
    'How can I cultivate virtue and excellence?',
    'What is the ideal form of government?',
    'How do I achieve eudaimonia (flourishing)?',
    'What is the relationship between knowledge and virtue?',
    'What are the cardinal virtues?',
    'How should we educate citizens?',
    'What is the nature of the Forms?',
    'How can I live according to reason?',
    'What is the best life for a human being?',
    'What did Socrates mean by "know thyself"?',
    'How can dialectic lead to truth?',
    'What is the difference between opinion and knowledge?',
    'What makes a just city?',
    'How should the philosopher-king rule?',
  ],
  'Stoic Philosophy': [
    'How can I control my emotions?',
    'What is within my control?',
    'How do I accept what I cannot change?',
    'What is living according to nature?',
    'How can I develop inner tranquility?',
    'What is the dichotomy of control?',
    'How should I respond to adversity?',
    'What does it mean to live virtuously?',
    'How can I be indifferent to external things?',
    'What is the path to inner freedom?',
    'How do I deal with anxiety about things I cannot control?',
    'What did the Stoics teach about facing death?',
    'How can I practice negative visualization?',
    'What is amor fati?',
    'How do I distinguish between what is up to me and what is not?',
  ],
  'Christian Theology & Philosophy': [
    'What is grace and how does it work?',
    'How can I know God?',
    'What is the nature of sin?',
    'How does faith relate to reason?',
    'What is salvation?',
    'What does it mean to love God and neighbor?',
    'How should I understand the Trinity?',
    'What is divine providence?',
    'How can I grow in holiness?',
    'What is the purpose of prayer?',
    'Does God exist? What are the arguments?',
    'Why do bad things happen to good people?',
    'What is the relationship between faith and works?',
    'How can I understand the incarnation?',
    'What is the beatific vision?',
  ],
  'Christian Mysticism': [
    'How can I experience union with God?',
    'What is contemplative prayer?',
    'How do I practice detachment?',
    'What is the divine spark within?',
    'How can I know God beyond concepts?',
    'What is mystical theology?',
    'How do I surrender to divine will?',
    'What is spiritual darkness?',
    'How can I experience divine presence?',
    'What is the inner Christ?',
    'What did Meister Eckhart mean by "letting go" (Gelassenheit)?',
    'How can God be born in my soul according to Eckhart?',
    'What did Jakob Böhme teach about light and darkness in God?',
    'What is the ground of being?',
    'How do I empty myself to be filled with God?',
  ],
  'Protestant Reformation': [
    'What is justification by faith alone?',
    'How can I be saved?',
    'What is the role of Scripture?',
    'What is the priesthood of all believers?',
    'How should I understand predestination?',
    'What is saving grace?',
    'How do I live by faith?',
    'What is Christian liberty?',
    'How should I read the Bible?',
    'What is the relationship between law and gospel?',
    'What did Martin Luther say about free will?',
    'What did John Calvin teach about predestination?',
    'What did the Reformers teach about grace and works?',
    'How should Christians respond to unjust rulers according to Knox?',
    'What is sola scriptura?',
  ],
  'Protestant Christianity': [
    'How can I be born again?',
    'What is sanctification?',
    'How do I grow in faith?',
    'What is the work of the Holy Spirit?',
    'How should I evangelize?',
    'What is genuine conversion?',
    'How can I serve God?',
    'What is Christian discipleship?',
    'How do I overcome sin?',
    'What is revival?',
    'How can I know if I am truly saved according to the Puritans?',
    'What did John Wesley mean by a heart "strangely warmed"?',
    "What is the Christian life like according to Bunyan's Pilgrim's Progress?",
    'What did Jonathan Edwards say about religious affections?',
    "How did Spurgeon balance God's sovereignty with evangelism?",
  ],
  'Christian Apologetics': [
    "What are the arguments for God's existence?",
    'How can I defend my faith?',
    'Is Christianity rational?',
    'How do faith and reason work together?',
    'What is the evidence for the resurrection?',
    'How do I respond to atheism?',
    'What makes Christianity unique?',
    'How can I answer objections to faith?',
    'What is the basis for morality?',
    'How does Christianity address suffering?',
    'What is the moral argument for God?',
    'How can I explain the problem of evil?',
    'What is mere Christianity?',
    'How do I answer the trilemma about Jesus?',
    'What is the paradox of Christianity?',
  ],
  'Eastern Philosophy': [
    'What is enlightenment?',
    'How can I end suffering?',
    'What is the nature of the self?',
    'How do I practice mindfulness?',
    'What is karma?',
    'How can I achieve nirvana?',
    'What is the middle way?',
    'How should I meditate?',
    'What is non-attachment?',
    'What is the path to liberation?',
    'What did Buddha teach about suffering?',
    'How should I treat others according to Confucius?',
    'What does the Bhagavad Gita teach about acting without attachment?',
    'How should I fulfill my duty when it conflicts with my desires?',
    'What is the Eightfold Path?',
  ],
  'Jewish Philosophy & Mysticism': [
    'What is the nature of Torah?',
    'How can I serve God with joy?',
    'What is the hidden meaning of Scripture?',
    'How do the sefirot reveal God?',
    'What is tikkun olam?',
    'How should I practice mitzvot?',
    "What is the soul's journey?",
    'How can I cleave to God?',
    'What is devekut?',
    'How do I repair my soul?',
    'What does Maimonides teach about knowing God through negation?',
    'How did the Baal Shem Tov teach we should serve God with joy?',
    'What is hitbodedut according to Rabbi Nachman of Breslov?',
    'What does it mean that "the whole world is a narrow bridge"?',
    'What did the Lubavitcher Rebbe teach about finding meaning in every moment?',
    'What is tzimtzum and why did God need to "contract" to create the world?',
    'What are the sefirot according to the Zohar?',
    'What does tikkun olam really mean in Kabbalah?',
  ],
  'Hermetic Philosophy': [
    'What is the principle of correspondence?',
    'How does the microcosm reflect the macrocosm?',
    'What is spiritual alchemy?',
    'How can I transform consciousness?',
    'What is the divine mind?',
    'How do I work with universal laws?',
    'What is the path of initiation?',
    'How does vibration work?',
    'What is the mystery of creation?',
    'How can I know the One?',
    'What are the seven Hermetic principles from the Kybalion?',
    'What does "as above, so below" really mean?',
    'How can I use the principle of mentalism to change my life?',
    'What is the Emerald Tablet?',
    'How do I transmute base consciousness into gold?',
  ],
  'Modern Philosophy': [
    'What is authentic existence?',
    'How do I create meaning in a meaningless world?',
    'What is the will to power?',
    'How can I overcome nihilism?',
    'What is existential freedom?',
    'How do I face absurdity?',
    'What is the Übermensch?',
    'How should I take responsibility for my choices?',
    'What is radical freedom?',
    'How can I find meaning in suffering?',
    'How do I find meaning in suffering according to Viktor Frankl?',
    'What is logotherapy and how can it help me?',
    'How do I find meaning after losing my faith?',
    'What did Frankl mean by "he who has a why can bear any how"?',
    'What is the leap of faith?',
  ],
};

// Default to general questions
export const STARTER_QUESTIONS = GENERAL_QUESTIONS;
